### ISSUE TITLE
multipart endpoints in Xray server are not being handled properly

### ISSUE THREAD

**Issue by bitcoder** [mikepenz/xray-action#222]
The current implementation of multipart endpoints is no accurate for Xray server/datacenter.
The JSON syntax for the "info" object is different from the existing syntax for Xray Cloud where "xrayFields" attribute is available (and not on server).
In Xray server/datacenter, Test Environments, Test Plan and the Revision are all standard custom fields available for Test Execution issues; in Xray Cloud this is different.
For defining the Test Environments, the Test Plan key, the Revision, or any other custom field, we need to identify the respective custom field id.. which  may be different from one Jira instance to the other...

Note: we can pair to clarify this, figure out a viable solutiomn and fix current implementation

**Comment by mikepenz** [comment]
@bitcoder thank you so much for the report. 

Please feel free to get in touch :) so we can have a closer look what needs to be changed to be fully compliant :)

**Comment by bitcoder** [comment]
Meawhile, I've used a "curl" workaround in this repo:

https://github.com/Xray-App/tutorial-js-cypress-cucumber/blob/main/.github/workflows/main-cloud.yml

**Comment by mikepenz** [comment]
@bitcoder I just realized that I am super late to come back to your comment. 

I suppose the alternative will be for the `cloud` API to require these fields to be passed via the test execution json? (and not have the action overwrite these?)

**Comment by bitcoder** [comment]
Whenever using the multipart endpoinst, you have to pass the test execution json and that format for server/DC is precisely equal to the Jira api endpoint for updating a jira issue.
Xray cloud has a "hack" where it supports the "xrayFields" element on that json that Xray Cloud will use to map to the correct attributes internally.
On Xray server/DC, the test environment and test plan are implemented as standard custom fields. So, what that means is that in order to update them, you need to use the standard Jira way to update those fields by referring them by customfield_<some_id>.
In sum, while on Xray cloud you can pass those attributes and map them to the xrayFields element, on Xray cloud unfortunately you cant. Therefore users will need to embed them on the test execution json themselves.

**Comment by mikepenz** [comment]
@bitcoder thank you very much. Opened a PR which should cover these elements: https://github.com/mikepenz/xray-action/pull/309

The `xrayFields` will no longer be set for `server/DC` environments. And the README highlights that `server/DC` environments require special attention,

**Comment by mikepenz** [comment]
Fixed in v2.0.0
