### ISSUE TITLE
Facing issue (Unexpected token B in JSON at position 0)

### ISSUE THREAD

**Issue by pdange** [mikepenz/xray-action#335]
Hi @mikepenz ,

Thanks for your plugin.  😄  

Currently I am facing one issue with cypress generated XML results with mocha-junit-reporter. I am trying to use the test merge option in the repo and below is the issue. Please find the attached output of GHA , `cyress.json` and YML file.

### - Cypress.json file : 
![image](https://user-images.githubusercontent.com/80270582/132970722-dc2ae75e-f7bb-4a59-9767-409e9cdcf8dc.png)

### - Below is the output of the GHA console : 

<img width="1388" alt="Screenshot 2021-09-12 at 04 12 00" src="https://user-images.githubusercontent.com/80270582/132970650-0ab53c6d-00e0-4b3b-ba0a-7d4a80fdc682.png">

### - GHA yml file : 

![image](https://user-images.githubusercontent.com/80270582/132970662-550c627f-db87-4c8f-8a78-395cf2df6275.png)

Can you please help here? 
Thanks in Advance.

**Comment by mikepenz** [comment]
Could you please update to the latest v2, we improved logging significantly so it should help to identify the issue. 

Based on the log it seems a invalid result was returned from the server, causing this failure.

**Comment by pdange** [comment]
@mikepenz 
Thanks for quick reply, I tried the same with version 2 the error I get is surprisingly different this time
### 1. GHA file 
![image](https://user-images.githubusercontent.com/80270582/133058523-54a1c070-1b88-490a-ba28-3c0bcae2a736.png)

### 2. Output on GHA resulting in failed run : 
![image](https://user-images.githubusercontent.com/80270582/133058757-c4029a9e-ee03-4227-8a6f-235e7a0eaa0e.png)

Please advise, Thanks a lot in advance.

Regards,
PD

**Comment by mikepenz** [comment]
Based on the screenshot it looks like the password is not provided. If you look at the `with` list, there is no entry for password showing up. 

Please make sure you provide it, and the SECRET is also properly specified.

**Comment by pdange** [comment]
In the old runs this was never the issue, because if you see the comment with which I created an issue with `@v1.1.0`,  `Connect to XRAY` step was successful not sure why is this failing in `v2`

Does this not look like error from plugin side in `v2`?

Regards,
PD

**Comment by mikepenz** [comment]
@pdange v1 did not yet verify the input to be valid. and lacked the verification for this value to be present. 

If you see. v2 checks the password to be filled here: https://github.com/mikepenz/xray-action/blob/main/src/main.ts#L38-L42 before anything else happens.

**Comment by pdange** [comment]
@mikepenz 
Ah sure, I get this now, I will check with the team for the secrets on Github. Thanks, will get back to you!

Regards,
PD

**Comment by pdange** [comment]
Hi @mikepenz , 
You were right, the password value is missing from git secrets, Is is possible to use an API Token from JIRA raw password instead?

Regards,
PD

**Comment by mikepenz** [comment]
@pdange according to the XRAY server/DC it requires username and password as basic authentication: 
https://docs.getxray.app/display/XRAY/v2.0

You can see how it is used inside the action here for example here: https://github.com/mikepenz/xray-action/blob/main/src/xray-server.ts#L107

You could try if the token is accepted instead of the password, but I can sadly only refer to the xray documentation in this case. 

Maybe @bitcoder would be able to chime in on this question?

**Comment by bitcoder** [comment]
Jira datacenter 8.14 added the support for personal access tokens.
You need to use a different authentication  header because of the token. No username is needed. Please check:

https://docs.getxray.app/display/XRAY/REST+API

**Comment by mikepenz** [comment]
Thank you @bitcoder will have a look. 

I believe can can move this new feature request in a new ticket, as the original issue should be answered @pdange ?

**Comment by pdange** [comment]
Yes please @mikepenz, till then I can check the one @bitcoder highlighted, thanks for that. 💯 

As even after adding the password in the Git Action I am getting an error :
![image](https://user-images.githubusercontent.com/80270582/133339855-57f5dc69-e510-4b51-8996-57510d61d234.png)

Yes may be it can be closed off and moved to a new feature. Is there an ETA as to when the feature will be availble with token/Authentication token used?

Regards,
PD

**Comment by mikepenz** [comment]
@pdange that's interesting. wondering why it would return this note instead of the expected json result. Especially if it is just a deprecation warning. 

You should be able to use the API-Token from JIRA instead of the password: https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/


No specific ETA, but I'll try to come to it sometimes this week

**Comment by pdange** [comment]
@mikepenz @bitcoder 
Hi,

Just to update you here on the progress, I have tried certain combinations of using the API token  #but nothing seems to work with `/rest/raven/2.0/import/execution/junit` 

- Have tried using `username:api_token` with curl command below 

> Error pops up as `404` null for uri 
> `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>404</status-code><message>null for uri: https://${JIRA_DOMAIN}/rest/api/3/projects?projectKey=ABC</message></status>%    `     

- Have tried using header `Authorization : Bearer ${encodedToken}` The encodedToken here is generated by encoding the `userName:api_token` Same 404 error is returned for this.

Can you please check if this is the case with you as well while importing Junit Results to JIRA? via curl command?

**Comment by mikepenz** [comment]
Opened a PR for token based authentication: https://github.com/mikepenz/xray-action/pull/340

Would be great to see if that works. (You can reference the SHA-1 of that branch in your GitHub Action and it will use that exact state)


In regards to your above note, I don't think you will need to base64 encode the token if you use the `Bearer`.

**Comment by bitcoder** [comment]
The bearer doesn't need to be base64  encoded

**Comment by pdange** [comment]
@bitcoder : The JIRA official page says so https://developer.atlassian.com/cloud/confluence/basic-auth-for-rest-apis/

I am checking the URL `/rest/raven/2.0/import/execution/junit` gives 404 even after encoding the token with the steps followed in above URL.

@mikepenz : Thanks for opening up the issue 👍🏾  

Regards,
PD

**Comment by bitcoder** [comment]
@pdange you can see here a code snippet in python using it. There are other code snippets , including for JS @mikepenz 

https://github.com/Xray-App/xray-code-snippets/blob/main/use_cases/import_automation_results/python/import_results_robot_standard.py

**Comment by pdange** [comment]
Hi @mikepenz : Hard luck!! Still gives an error.

![image](https://user-images.githubusercontent.com/80270582/133778421-7784c7dc-0008-461f-b398-90eca26b1fa4.png)

Thanks @bitcoder, will try an python code you sent.
Thanks.
PD

**Comment by mikepenz** [comment]
The screenshot would indicate that you did not provide the token, but instead configured username and password?
If you have the token for server/DC then it would expect it as `xrayToken`: https://github.com/mikepenz/xray-action/pull/340/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R21-R23
And instead remove `username` and `password` please

Ultimately that's the server response here: https://github.com/mikepenz/xray-action/blob/main/src/utils.ts#L93-L98

**Comment by pdange** [comment]
Okay awesome, looks like the authentication error is gone, but still it is unable to parse the junit xml file, facing the same issue in parsing the file.
![image](https://user-images.githubusercontent.com/80270582/133784049-2cc1668e-964b-43a7-bf12-f5fe96dbfb80.png)

**Comment by mikepenz** [comment]
At this point I am wondering, maybe the installation of xray (server/DC) is outdated and does not yet have these endpoints? 

Could you also please verify that this is a server/DC installation and not a normal jira cloud environment?

**Comment by pdange** [comment]
Hi @mikepenz  How are you keeping?

Apologies for the delay here, recently found out the installation is XRay-Cloud. So was able to get the client ID and Client Secret.  But I was wondering is it possible to change the URL here in [Xray-Cloud.ts](https://github.com/mikepenz/xray-action/blob/main/src/xray-cloud.ts#L16) 

I have got it working via the curl command in local, but my URL is different than the one mentioned above. So is it possible to have the baseURL a parameter? when we use Xray-cloud.

Note : I haven't tried using this in a pipeline, there are few steps to get those client ID and secret to be added to Github, so that is pending.

**Comment by bitcoder** [comment]
Hi @pdange , the Xray Cloud API endpoint is non-customizable; it's vendor specific and always the same

**Comment by mikepenz** [comment]
@pdange you have configured `xrayCloud` to be `false` in the above screenshot. 

Are you using `cloud`, or are you using `server/DC`?

**Comment by pdange** [comment]
@mikepenz @bitcoder , I have the curl command working with the username and password and my url as `https://xray.cloud.xpand-it.com` But it is throwing error when I use the plugin on Github Action. Please check below

![image](https://user-images.githubusercontent.com/80270582/135293747-e80bfecd-9e07-4b75-804c-f449ac2d2d45.png)

Regards,
PD

**Comment by mikepenz** [comment]
Given the screenshot it looks like there is no `testExecJson` and `testExecKey` 

So it will go this path: https://github.com/mikepenz/xray-action/blob/b83be0289cf94bf57f06622d8e9e06de777468bc/src/xray-cloud.ts#L132

The error is the one returned from the xray API. 
Looks like maybe username and password are not correct. 

Not sure which other scenarios can lead to that message from the official xray API
