### ISSUE TITLE
Failed to authenticate with Xray: RequestError: certificate has expired

### ISSUE THREAD

**Issue by mtausgondal** [mikepenz/xray-action#451]

**Comment by mikepenz** [comment]
@mtausgondal I fear this is no problem of the action. Sounds like the ssl certificate to the endpoint you try to access is no longer valid

**Comment by mtausgondal** [comment]
Can you please elaborate a bit more? I am really confused because the workflow that I used to have worked before

**Comment by mtausgondal** [comment]
`name: Test Execution and Reporting to Xray
on:
  workflow_dispatch:
    inputs:
      test_plan_key:
        description: 'Test Plan issue key'
        required: false
        default: ''
      test_exec_key:
        description: 'Test Execution issue key'
        required: true
        default: ''
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_MANAGER_EMAIL:  ${{ secrets.MANAGER_EMAIL }}
        CYPRESS_MANAGER_PASSWORD:  ${{ secrets.MANAGER_PASSWORD }}
        CYPRESS_LABELLER_EMAIL:  ${{ secrets.LABELLER_EMAIL }}
        CYPRESS_LABELLER_PASSWORD:  ${{ secrets.LABELLER_PASSWORD }}
    - name: "Import results to Xray"
      uses: mikepenz/xray-action@v0.9.4
      if: always()
      with:
        username: ${{ secrets.XRAY_CLIENT_ID }}
        password: ${{ secrets.XRAY_CLIENT_SECRET }}
        testFormat: "junit"
        testPaths: "**/results/*.xml"
        projectKey: "IAIT"
        testPlanKey: ${{ github.event.inputs.test_plan_key }}
        testExecKey: ${{ github.event.inputs.test_exec_key }}`

**Comment by mtausgondal** [comment]
name: Test Execution and Reporting to Xray
on:
  workflow_dispatch:
    inputs:
      test_plan_key:
        description: 'Test Plan issue key'
        required: false
        default: ''
      test_exec_key:
        description: 'Test Execution issue key'
        required: true
        default: ''
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_MANAGER_EMAIL:  ${{ secrets.MANAGER_EMAIL }}
        CYPRESS_MANAGER_PASSWORD:  ${{ secrets.MANAGER_PASSWORD }}
        CYPRESS_LABELLER_EMAIL:  ${{ secrets.LABELLER_EMAIL }}
        CYPRESS_LABELLER_PASSWORD:  ${{ secrets.LABELLER_PASSWORD }}
    - name: "Import results to Xray"
      uses: mikepenz/xray-action@v0.9.4
      if: always()
      with:
        username: ${{ secrets.XRAY_CLIENT_ID }}
        password: ${{ secrets.XRAY_CLIENT_SECRET }}
        testFormat: "junit"
        testPaths: "**/results/*.xml"
        projectKey: "IAIT"
        testPlanKey: ${{ github.event.inputs.test_plan_key }}
        testExecKey: ${{ github.event.inputs.test_exec_key }}

**Comment by mtausgondal** [comment]
This is my workflow file, what can be wrong in this?

**Comment by mikepenz** [comment]
As noted above, it looks like the SSL certificate is expired: `RequestError: certificate has expired` 

This action is now v2.3.0 and your build still uses v0.9.4. 

I believe the API URL changed from Xray since: 
https://github.com/mikepenz/xray-action/blob/v0.9.4/src/xray.ts#L9
vs:
https://github.com/mikepenz/xray-action/blob/main/src/xray-cloud.ts#L16

**Comment by mtausgondal** [comment]
Ah I realized that too. Thank you so much Mike for your reply. Cheers!

**Comment by mikepenz** [comment]
<img width="969" alt="Screenshot 2022-01-27 at 10 53 09" src="https://user-images.githubusercontent.com/1476232/151335144-56cc98c7-5dd8-475e-85a9-f6b0f081e8f0.png">

As you can see, it expired on the 18th of January. There's nothing from side of the action we can do. 

You will most likely have to update to the latest version, so you can make use of their new API

**Comment by mtausgondal** [comment]
Hey Mike, I just realized skipped tests does not get imported to Xray. What can be the reason for this?

**Comment by mikepenz** [comment]
Closing as it is not an issue of the action. 

For the second question. The action will take the exported report, and as a whole import into xray. 
You may want to check with xray directly using their api and see if it behaves the same.
