### ISSUE TITLE
Unable to import results from serenity to x-ray

### ISSUE THREAD

**Issue by sahni619** [mikepenz/xray-action#457]
Hi,

I am facing this issue with the action. It is configured, and running but it's not importing results from the .html file to x-ray.

If you see below screenshot, I get no error, but it just doesn’t import anything

<img width="580" alt="Screenshot 2022-02-11 at 7 09 31 PM" src="https://user-images.githubusercontent.com/17097887/153601539-338333f8-f2c5-4cc4-ac0e-855ef48dc825.png">

Can any one help with this issue?

**Comment by mikepenz** [comment]
@sahni619 given the screenshot it looks like it did not find any files. 

Are you sure there are reports in the defined path? Also (I am not an expert in cucumber specifically) but are those really `.html` reports? 

Based on the official doc it looks they should be `.feature` files? https://docs.getxray.app/display/XRAY/Importing+Cucumber+Tests+-+REST

**Comment by sahni619** [comment]
Thanks @mikepenz for chiming in. So, when I run my project on my local using mvn clean verify, it generates a target folder with index.html. This file when opened in chrome have all the information like the features I have written to test.

I also tried to use testPaths: "**/test/features/*.feature" because that's where my feature file resides, but it does the same thing.

But I am not sure if the endpoint which is mentioned in the docs is configured in the action?

**Comment by mikepenz** [comment]
The `*.html` file is usually the report which is only meant for direct viewing things. but usually reports imported into systems are in a different format (like the documentation in `*.feature`) 


The action retrieves files via this method herE: 
https://github.com/mikepenz/xray-action/blob/main/src/processor.ts#L84-L88

https://github.com/mikepenz/xray-action/blob/main/src/utils.ts#L115-L118

Given this log message here: 
https://github.com/mikepenz/xray-action/blob/main/src/processor.ts#L155

The globber could not find any files matching your path definition. 


Looks like `"**/test/features/*.feature"` does not lead to results

**Comment by sahni619** [comment]
<img width="995" alt="Screenshot 2022-02-12 at 3 47 43 PM" src="https://user-images.githubusercontent.com/17097887/153707256-ffaf2f06-73fc-49b9-a63f-5cebb95f1bf6.png">

**Comment by sahni619** [comment]
Closed by mistake

**Comment by sahni619** [comment]
I did some changes in the path and now it gives me above issue. Thanks for your support @mikepenz

**Comment by mikepenz** [comment]
Do you have the cucumber export as json? Cucumber json reports are supported.

I am sorry that I forgot about it, but `*.feature` files are not yet supported. Please see here: https://github.com/mikepenz/xray-action/issues/320

**Comment by sahni619** [comment]
<img width="950" alt="Screenshot 2022-02-15 at 6 49 21 PM" src="https://user-images.githubusercontent.com/17097887/154069997-8d0a0748-c045-448d-bd62-face0299dbd8.png">

So, I tried the json as well. I am getting cucumber-reports in json format, but still unable to import. Not sure why. Is there something I may be missing?

**Comment by mikepenz** [comment]
Please report back, otherwise will close for inactivity

**Comment by mohit597** [comment]
Hi @sahni619 Can you please help me solve this error. 
Getting 400 bad request while importing the test results: Message:BadRequest url=https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=stu&TestPlanKey="stu453"
Command: mvn clean compile test xray:import-results
In pom.xml gives:
<plugin>
            <groupId>app.getxray</groupId>
            <artifactId>xray-maven-plugin</artifactId>
            <version>0.7.3</version>
            <scope>test</scope>
            <configuration>
                <clientId>215FFD69FE46447280000000000</clientId>
                <clientSecret>1c00f8f22f56a8684d7c18cd61470000000</clientSecret>
                <cloud>true</cloud>
                <projectKey>CALC</projectKey>
                <fixVersion>1.0</fixVersion>
                <reportFormat>junit</reportFormat>
                <reportFile>target/cucumber.xml</reportFile>
            </configuration>
        </plugin>
