### ISSUE TITLE
Authentication failed - Xray Cloud REST API is now https only?

### ISSUE THREAD

**Issue by mrudatsprint** [mikepenz/xray-action#528]
On July 4, we started seeing `Failed to authenticate with Xray: RequestError: connect ECONNREFUSED` when uploading to Xray Cloud from workflows.

It appears the REST API is now https only.  I ran a few curl commands and https worked whereas http resulted in `Connection refused`

- http
- `curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$CLIENT_ID\",\"client_secret\": \"$CLIENT_SECRET\" }" http://xray.cloud.getxray.app/api/v2/authenticate`
- `Failed to connect to xray.cloud.getxray.app port 80 after 1058 ms: Connection refused`

- https
- `curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$CLIENT_ID\",\"client_secret\": \"$CLIENT_SECRET\" }" https://xray.cloud.getxray.app/api/v2/authenticate`
- An authorization token was returned

xray-cloud.ts is referencing `http://xray.cloud.getxray.app`

Thank you for looking into the issue.

**Comment by mikepenz** [comment]
Please re-test with v2.4.2 Thank you very much
