### ISSUE TITLE
Warnings "The `set-output` command is deprecat"

### ISSUE THREAD

**Issue by robozor** [mikepenz/xray-action#609]
Thanks for the great helper to export test results to Jira.
I would need help solving warnings. 
Do you have any recommendations?

![obrazek](https://user-images.githubusercontent.com/7280092/200822820-d0caaa1e-d6f3-4b9e-97c0-c0e29dfb6ba8.png)
Thank you

**Comment by mikepenz** [comment]
@robozor thank you for the report. 

We'll have to update the action to use the latest GitHub NPM dependencies to resolve the warning. 

Will look into it in the upcoming days

**Comment by mikepenz** [comment]
Updated the `actions/core` dependency and released as v2.4.4
