### ISSUE TITLE
Enhance error messages instead of general 400 Bad Request response

### ISSUE THREAD

**Issue by jengland-victorfi** [mikepenz/xray-action#735]
https://github.com/mikepenz/xray-action/issues/692 - I thought this was closed but it failed for me.

```      - name: Post to jira
        uses: mikepenz/xray-action@v3.0.2
        if: ${{ inputs.publishToJira && !cancelled()}}
        with:
          username: ${{ secrets.xrayClientId }}
          password: ${{ secrets.xrayClientSecret }}
          testFormat: "junit"
          testPaths: "**/newman/*.xml"
          testExecKey: "TA-1"
          projectKey: "TA"
```
 Error
 `Warning: 🔥 Failed to import: /home/runner/work/postman-runner/postman-runner/newman/newman-run-report-2023-11-08-22-42-11-631-0.xml (HTTPError: Response code 400 (Bad Request))`

**Comment by mikepenz** [comment]
Thank you for the report. This is being logged here: https://github.com/mikepenz/xray-action/blob/main/src/processor.ts#L115

It may be that the error thrown by the http framework doesn't expose more details. Going to adjust to stringify this object, maybe this adds more context.

**Comment by mikepenz** [comment]
If you could please check recheck with v3.0.3
