### ISSUE TITLE
Request to Add responseTimeout as a Configurable Input in xray-action

### ISSUE THREAD

**Issue by den-cezar** [mikepenz/xray-action#893]
Hello,

I have been using the `mikepenz/xray-action@v3.0.4` for automating the import of test results to Xray in my CI/CD workflows. Recently, I encountered a situation where I needed to set a custom timeout for the response from the server during the import process. After checking the action's documentation and attempting to use `responseTimeout` as a configurable parameter, I was presented with the following warning:

```
Warning: Unexpected input(s) 'responseTimeout', valid inputs are ['xrayCloud', 'xrayBaseUrl', 'username', 'password', 'xrayToken', 'testPaths', 'testMerge', 'testFormat', 'testExecKey', 'projectKey', 'testPlanKey', 'testEnvironments', 'revision', 'fixVersion', 'combineInSingleTestExec', 'failOnImportError', 'continueOnImportError', 'importParallelism', 'testExecutionJson', 'testJson']
```

It appears that `responseTimeout` is not a recognized input for the current version of xray-action. I believe having the ability to specify a custom timeout could be beneficial, particularly in cases where network conditions or server response times vary.

Could we consider adding `responseTimeout` as an official input parameter in future releases of xray-action? This feature would provide users with greater flexibility in managing their workflow's interaction with Xray, especially in environments with less predictable response times.

Thank you for considering this enhancement. I look forward to any updates on this matter.

Best regards, 
Denys.

**Comment by mikepenz** [comment]
Good day. 

The response timeout was only introduced in 3.1.0 (or newer): https://github.com/mikepenz/xray-action/releases/tag/v3.1.0

You are using a version which does not support that yet. When using older versions please always refer to the README of that particular version for details on what it supports: https://github.com/mikepenz/xray-action/tree/v3.0.4

**Comment by den-cezar** [comment]
Got it, many thanks for the clarification. That works as expected. I'm closing this conversation.
