### ISSUE TITLE
Can't handle multiple .trx (xunit) files

### ISSUE THREAD

**Issue by fclante** [mikepenz/xray-action#929]
📝 Import test reports
  ℹ️ Importing from: **/test-results/*.trx
  ℹ️ Importing using format: xunit
  ℹ️ xunit does currently not support test result merging

- It would be nice if the action could handle each file separately instead of failing.

I know that I could just call the action for each .trx file my project generates, but that doesn't help when I'm using this action from within a composite action that doesn't support matrix jobs.

**UPDATE** 

I found [this](https://github.com/ricardofslp/dotnet-trx-merge) tool, which solves it for the time being, but it would be nice if this action did it ;-)

- dotnet tool install --global dotnet-trx-merge

**Comment by bitcoder** [comment]
@fclante I don't think .trx file format and xUnit XML format are the same. Xray doesn't support .trx files

**Comment by mikepenz** [comment]
Thanks @bitcoder for responding. 

@fclante at this time we don't plan in this action to support merging non xml or json files into a single report.
